### ISSUE TITLE
Add environments

### ISSUE THREAD

**Issue by dasch** [dasch/starfish#6]
Reasons to even have environments:
1. Common config across channels.
2. Maps to different Mesos/whatever clusters.
3. Common release policies, e.g. buddy-required.
###### Tasks
- [ ] Allow listing the environments and the pods in the environments: #11.
- [ ] Allow hooking channels up to environments.
- [ ] Let the environments decide on approval policy.
- [ ] Allow dynamically defining environments.

**Comment by dasch** [comment]
Alternatives to "environment": datacenter; cluster.
